name: yaml_test_suite_dart
description: >-
  Dart script for adapting the official YAML test suite to suite parsers
  written in Dart
version: 0.0.1
repository: https://github.com/kekavc24/yaml_test_suite_dart

environment:
  sdk: ^3.8.0
  
dependencies:
  args: ^2.7.0
  async: ^2.13.0
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
